### ISSUE TITLE
Task: Implement different UI Screens According to Mockup

### ISSUE THREAD

**Issue by ppebb** [ppebb/isp2#16]
Addresses story #6
Follow the UI mockups for each screen here: 
https://www.figma.com/file/obwV3rG7iyfHXlT45ct7Y6/Untitled?type=design&node-id=0%3A1&mode=design&t=JWjJYNkxq5ggzoDw-1

**Comment by Nathan-Goldman** [comment]
Possible fancy big texts for menus.
https://docs.google.com/document/d/184LQUBdWp-1AmDt4g1sFRYm1jmiGB8PZxnsk6QRHsaE/edit?usp=sharing
