### ISSUE TITLE
Task: Create colorscheme and implement in colors, color pairs, and highlight groups

### ISSUE THREAD

**Issue by ppebb** [ppebb/isp2#50]
Implement a set of base colors to work with (standard rainbow colors as well as things like text and background colors)

Addresses story #49.

**Comment by Nathan-Goldman** [comment]
Doc for color codes for the color scheme. Still a WIP at the moment.
https://docs.google.com/document/d/15MIz2JjUXJmSPYGmhDNRXqYotfyJCVHt_bsnPAlrP5E/edit?usp=sharing

**Comment by Nathan-Goldman** [comment]
Full scheme of 51 colors has been implemented. 

Full scheme in image form:
https://drive.google.com/file/d/1F7ukyPN81tP4Xpays5CngFtQ8vaMj8UD/view?usp=sharing.

RGB values for the full scheme in text form:
https://docs.google.com/document/d/15MIz2JjUXJmSPYGmhDNRXqYotfyJCVHt_bsnPAlrP5E/edit?usp=sharing
