### ISSUE TITLE
Task: Create Mockup of Menu Color Scheme

### ISSUE THREAD

**Issue by Nathan-Goldman** [ppebb/isp2#63]
Create a mockup of potential color schemes for menus.

Addresses story #49.

**Comment by Nathan-Goldman** [comment]
Primary candidate mockups can be viewed here
https://drive.google.com/file/d/1JUVicdLBMyHdkSmZXbID5JsBkMvZWOd7/view?usp=sharing

All mockups can be viewed through importing the following file into this site https://pixlr.com/editor/
https://drive.google.com/file/d/153fcST7HWivne0i7-bwrf-9w8QXvWWWP/view?usp=sharing

**Comment by ppebb** [comment]
Bottom left looks good for a start. Can you add them into code (as described in task #50) and make sure to include additional colors (i.e. the full rainbow)?
