### ISSUE TITLE
Task: Begin research to create a server for leaderboard scores

### ISSUE THREAD

**Issue by ppebb** [ppebb/isp2#66]
Look into what would be needed to create a leaderboard and how it could be implemented both server and client side. Do we want account based authentication or do we just want a simple api with an upload endpoint with no verification? By what metric will we measure completion? What will we use to create the server?

I already have a domain (https://ppeb.me) and a server (the one running the domain) available for use, so those do not need to be considered.

Addresses story #5

**Comment by Derate11** [comment]
https://docs.google.com/document/d/18OZp5hbmRXF5HiBIs-26YEYUsRV_xJCYUQgubhSXX38/edit?usp=sharing
